FROM ubuntu:16.04

WORKDIR /appsi
COPY frontend-example-docker-master frontend-example-docker

RUN apt update && apt install -y curl && curl -sL https://deb.nodesource.com/setup_10.x | bash && apt install -y nodejs && \
apt-get purge -y --auto-remove curl && \
rm -rf /var/lib/apt/lists/* && \
useradd -m app && chown -R app /appsi

USER app

CMD cd frontend-example-docker && npm install && npm start
