FROM ubuntu:16.04

WORKDIR /appsi
COPY backend-example-docker-master backend-example-docker

RUN apt update && apt install -y curl && curl -sL https://deb.nodesource.com/setup_10.x | bash && apt install -y nodejs && \
apt-get purge -y --auto-remove curl && \
rm -rf /var/lib/apt/lists/* && \
useradd -m app && chown -R app /appsi

USER app

ENV FRONT_URL=http://localhost:5000
CMD cd backend-example-docker && npm install && npm start
