FROM ubuntu:16.04

WORKDIR /appsi
COPY frontend-example-docker-master frontend-example-docker

RUN apt update
RUN apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt install -y nodejs
RUN node -v && npm -v

RUN cd frontend-example-docker && npm install

CMD cd frontend-example-docker && npm start
